### ISSUE TITLE
Keep directory tree structure for output

### ISSUE THREAD

**Issue by zengfanfan** [NCrashed/JuicyPixels-blp#1]
When use a folder path as input,  the output files are put together, I think it's more reasonable to keep the tree structure.
what do you think?

P.S. It's a really nice work, do exactly what I want. thx!

**Comment by NCrashed** [comment]
Yep, I also think that it is better to preserve the tree structure. I will see how to achieve this.

**Comment by NCrashed** [comment]
Try version 0.2.0.0 with this feature.

**Comment by zengfanfan** [comment]
> Try version 0.2.0.0 with this feature.

Checked. It works like a charm. 
![PWP2NCYHK$1{ 5B~{X3{`V2](https://user-images.githubusercontent.com/8079595/138924654-f8ccd882-e20f-406e-9eaf-4ca9f86a9517.png)
