### ISSUE TITLE
Error when convert this png

### ISSUE THREAD

**Issue by zengfanfan** [NCrashed/JuicyPixels-blp#2]
[Log]
```
path\to\blp2any convert workpath\HumanCursor.png workpath\.build\HumanCursor.blp --input-format png -f blp --quality 75 --blpFormat jpg
blp2any: .\Data\Vector\Generic.hs:245 ((!)): index out of bounds (8,8)
CallStack (from HasCallStack):
  error, called at .\Data\Vector\Internal\Check.hs:87:5 in vector-0.12.0.1-4FlkEWKNqrgLl7wn5Cpq3g:Data.Vector.Internal.Check
```

[The Source File]
![HumanCursor](https://user-images.githubusercontent.com/8079595/136660631-a20d6f2b-3162-478a-a76c-1379bf4ff5b4.png)

Help, anyone?

**Comment by NCrashed** [comment]
Hi, I will check the issue.

**Comment by NCrashed** [comment]
@zengfanfan please try with the new version

**Comment by zengfanfan** [comment]
Checked. it works as expected. nice! 
![33ZP(L0_BU5T9%IEMWO_`OE](https://user-images.githubusercontent.com/8079595/138923329-453cd6b3-823a-494c-b0c0-ea9990283a4d.png)

**Comment by zengfanfan** [comment]
And one more question:
How to reduce the exe size?
-- My newly built exe has size of **28.7MB** (while your 'first release' is only **11.6MB**)

Here is how I build it:
1. install ghcup on my win10 with: (command given by the official site)
```
Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $true
```
2. run `cabal install` in the project folder

**Comment by NCrashed** [comment]
I managed to reduce the size to **23MB** by enabling the option in `stack.yaml`:
```
ghc-options:
    "$everything": -split-sections
```
I pushed the change to master. But, I had no success to reduce the size more than that.

**Comment by zengfanfan** [comment]
OK, cool.
 I guess some dependency or lib grow the size...

Thank you for the try.
![S16J%}G5STEFO11Q%{2H 59](https://user-images.githubusercontent.com/8079595/138977942-5f69f008-b540-4c76-b2d9-57090427b289.png)
